module.exports = {
  handler: require("./handler"),
  connection: require("./connection"),
  function: require("./function"),
  database: require("./database"),
  fontManager: require("./fontManager"),
  getSettings: require("./getSettings"),
  bio: require("./bio"),
  channel: require("./channel"),
  newsletter: require("./newsletter"),
  welcome: require("./welcome"),
  logics: require("./logics"),
  web: require("./web"),
  tg: require("./tg"),
  isMaster: require("./isMaster"),
  isOwner: require("./isOwner"),
  isSudo: require("./isSudo"),
  isNormal: require("./isNormal"),
  isAdmin: require("./isAdmin"),
  permissions: require("./permissions"),
  botStore: require("./botStore"),
  cmdutil: require("./cmdutil"),
  jid: require("./jid"),
  coreConfig: require("./coreConfig"),
};
